inu-appcenter/ingle-server

- src/main/java/com/example/ingle/domain/member/enums/Department.java
- closed #5 
- 대학원 학과 추가 및 Dept 형태 통일
- ❌
> ♻️ refactor : 대학원 학과 추가 및 Dept 형태로 통일

- src/main/java/com/example/ingle/global/config/MysqlConfig.java
- src/main/java/com/example/ingle/global/config/OracleConfig.java
- closed #1 
- Mysql, Oracle 충돌을 해결하기 위한 다중 데이터 소스를 사용한 분리
- ❌
> 🐛 fix : Mysql, Oracle 다중 데이터 소스를 사용한 분리 - #1

- src/main/java/com/example/ingle/domain/member/Member.java
- src/main/java/com/example/ingle/global/BaseEntity.java
- closed #1 
- BaseEntity camel case 수정
- ❌
> 🔧 chore : BaseEntity camel case 수정 - #1

- src/main/java/com/example/ingle/global/config/MysqlConfig.java
- closed #1 
- EntityManagerFactory 직접 커스터마이징 시 발생하는 spring.jpa 설정 무시 해결
- ❌
> 🐛 fix : EntityManagerFactory 직접 커스터마이징 시 발생하는 spring.jpa 설정 무시 해결 - #1

- src/main/java/com/example/ingle/domain/member/controller/AuthApiSpecification.java
- closed #1 
- Auth 부분 스웨거 에러 명시 구체화
- ❌
> 📝 docs : Auth 부분 스웨거 에러 명시 구체화

- src/main/java/com/example/ingle/domain/map/MapService.java
- src/main/java/com/example/ingle/domain/member/Member.java
- src/main/java/com/example/ingle/domain/member/controller/AuthController.java
- src/main/java/com/example/ingle/domain/member/controller/MemberApiSpecification.java
- src/main/java/com/example/ingle/domain/member/controller/MemberController.java
- src/main/java/com/example/ingle/domain/member/dto/req/UpdateMemberRequestDto.java
- src/main/java/com/example/ingle/domain/member/dto/res/LoginResponseDto.java
- src/main/java/com/example/ingle/domain/member/dto/res/MyPageResponseDto.java
- src/main/java/com/example/ingle/domain/member/service/AuthService.java
- src/main/java/com/example/ingle/domain/member/service/MemberService.java
- closed #24 
- 마이페이지 api
- 서버 환경 테스트 필요
> ✨ feat : 마이페이지

- src/main/java/com/example/ingle/domain/member/controller/AuthApiSpecification.java
- src/main/java/com/example/ingle/domain/member/controller/AuthController.java
- src/main/java/com/example/ingle/global/config/SecurityConfig.java
- closed #1 
- Spring Security + 닉네임 중복 확인 로직 Param 형식으로 수정
- ❌
> 🔧 chore : Spring Security + 닉네임 중복 확인 로직 Param 형식으로 수정

- src/main/java/com/example/ingle/domain/map/Map.java
- src/main/java/com/example/ingle/domain/map/dto/res/MapDetailResponseDto.java
- closed #7 
- chore : 호관 필드명 buildingNumber로 변경
- ❌
> 🔧 chore : 호관 필드명 buildingNumber로 변경

- src/main/java/com/example/ingle/domain/member/enums/Program.java
> 🔧 chore : 학적 상태 수정

- src/main/java/com/example/ingle/domain/map/Map.java
- closed #7 
- 건물 정보 휴무일 추가
- ❌
> 🔧 chore : 건물 정보 휴무일 추가 

- src/main/java/com/example/ingle/domain/building/dto/res/BuildingDetailResponse.java
- src/main/java/com/example/ingle/domain/building/dto/res/BuildingResponse.java
- src/main/java/com/example/ingle/domain/member/dto/req/JwtTokenRequest.java
- src/main/java/com/example/ingle/domain/member/dto/res/LoginSuccessResponse.java
- src/main/java/com/example/ingle/domain/member/dto/res/MyPageResponse.java
- src/main/java/com/example/ingle/domain/member/dto/res/SignupRequiredResponse.java
- src/main/java/com/example/ingle/domain/member/repository/INUMemberRepository.java
- src/main/java/com/example/ingle/domain/member/repository/INUMemberRepositoryImpl.java
- src/main/java/com/example/ingle/domain/member/repository/INUMemberRepositoryMock.java
- src/main/java/com/example/ingle/domain/member/service/AuthService.java
- src/main/java/com/example/ingle/global/jwt/JwtProvider.java
- closed #1 
- Oracle 접근 Repository 인터페이스화
- ❌
> ♻️ refactor : Oracle 접근 Repository 인터페이스화

- .github/workflows/CI_CD.yml
- build.gradle
- src/main/java/com/example/ingle/domain/building/service/BuildingService.java
- src/main/java/com/example/ingle/global/config/RedisCacheConfig.java
- src/main/resources/application-prod.yml
> refactor : Redis를 활용한 지도 범위 조회 캐시화

- .github/workflows/CI_CD.yml
- src/main/resources/application-prod.yml
> fix : 도커 네트워크 연결

- src/main/java/com/example/ingle/global/config/RedisCacheConfig.java
- Record DTO 역직렬화를 위한 ObjectMapper 처리
- ❌
> fix : Record DTO 역직렬화를 위한 ObjectMapper 처리

- .github/workflows/CI_CD.yml
> 🐛 fix : env 처리 Git Actions로 주입

- src/main/java/com/example/ingle/domain/stamp/entity/Stamp.java
- close #71
- Stamp가 BaseEntity를 상속받지 않는 문제 개선
- ex) 성능 개선 필요
> 🐛 fix : Stamp가 BaseEntity를 상속받지 않는 문제 개선

- src/main/java/com/example/ingle/domain/stamp/entity/Stamp.java
- close #73 
- 이번 PR에서 작업한 내용을 간략히 요약해 주세요.
- ex) 성능 개선 필요
> 🐛 fix : Swagger 보안 스키마 네이밍 불일치 해결 - #73

- src/main/java/com/example/ingle/domain/stamp/StampService.java
- src/main/java/com/example/ingle/domain/stamp/controller/StampApiSpecification.java
- src/main/java/com/example/ingle/domain/stamp/entity/Stamp.java
- src/main/java/com/example/ingle/domain/stamp/res/CompleteTutorialResponse.java
- src/main/java/com/example/ingle/domain/stamp/res/StampResponse.java
- src/main/java/com/example/ingle/domain/tutorial/Tutorial.java
- src/main/java/com/example/ingle/domain/tutorial/TutorialRepository.java
- src/main/java/com/example/ingle/domain/tutorial/controller/TutorialApiSpecification.java
- src/main/java/com/example/ingle/domain/tutorial/dto/res/TutorialResponse.java
- close #73 
- 이번 PR에서 작업한 내용을 간략히 요약해 주세요.
- ex) 성능 개선 필요
> ♻️ refactor : 불필요한 response값 제거 및 isCompleted 반환

- src/main/java/com/example/ingle/domain/image/service/ImageService.java
- src/main/java/com/example/ingle/domain/member/service/AuthService.java
- src/main/java/com/example/ingle/domain/member/service/MemberService.java
- src/main/java/com/example/ingle/global/jwt/JwtFilter.java
- src/main/java/com/example/ingle/global/jwt/JwtProvider.java
> ♻️ refactor : 전체적인 코드 정리

- src/main/java/com/example/ingle/domain/building/domain/Building.java
- src/main/java/com/example/ingle/domain/building/dto/res/BuildingDetailResponse.java
- closed #7 
- 건물 정보 url 추가
- ❌
> 🐜 fix : 건물 정보 url 추가

- src/main/java/com/example/ingle/domain/building/service/BuildingService.java
- closed #7 
- 건물 이미지 요청 값 null일 경우 이미지만 삭제
- ❌
> 🐜 fix : 건물 이미지 요청 값 null일 경우 이미지만 삭제

- src/main/java/com/example/ingle/global/config/SecurityConfig.java
- src/main/java/com/example/ingle/global/jwt/JwtFilter.java
- close #92 
- JwtFilter와 SecurityConfig에 image 명시 
- 배포 서버 테스트 필요
> ♻️ refactor : 이미지 조회API 토큰 제거

- .github/workflows/CI_CD.yml
- src/main/java/com/example/ingle/domain/member/controller/AuthApiSpecification.java
- src/main/java/com/example/ingle/domain/member/controller/AuthController.java
- src/main/java/com/example/ingle/domain/member/domain/Member.java
- src/main/java/com/example/ingle/domain/member/service/AuthService.java
- src/main/resources/application-prod.yml
- closed #1 
- 공통 관리자 회원 생성
- 관리자 회원 로그인 로직 추가
- DB에 관리자 회원 추가 필요
> ✨ feat: 공통 관리자 회원 생성 및 관리자 회원 로그인 로직 추가

- .github/workflows/CI_CD.yml
- src/main/java/com/example/ingle/domain/member/repository/MemberRepository.java
- src/main/java/com/example/ingle/domain/member/service/AuthService.java
- src/main/java/com/example/ingle/domain/member/service/MemberQueryService.java
- src/main/resources/application-prod.yml
- closed #1 
- ADMIN_USERNAME은 DB에서 조회하도록 수정
- ❌
> 🔧 chore : ADMIN_USERNAME은 DB에서 조회하도록 수정
